POST http://127.0.0.1:8080/mail HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6IiIsImV4cCI6MTYyMjc1Mjg0OCwiaXNzIjoiTWFpbCJ9.pr038EFKkrC-_bl6BX3yklv67OC8GtTotYlSGsu58rc

{
    "to": "mathieu.scolas@craftlabit.be",
    "subject": "test subject",
    "body": "test content"
}